### ISSUE TITLE
Priorities (tracker)

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/product-packager#76]
- [ ] Output files directly to the desired paths #68
- [ ] Integrate the GDScript mini parser (unlocks the ability to include symbols) #
- [ ] Change the icon preprocessing #73 
- [ ] Replace the rehype plugins in GDSchool
- [ ] Refactor: move #ANCHOR: ... parsing to the GDScript parser
- [ ] Improve performance - likely parse one file per core
- [ ] Update preprocessor to output html. Port [transformCustomHTMLTags.ts](https://github.com/GDQuest/process-course-utils/blob/5c02906dcf18ede62b40b029173837649c80ceb2/src/transformCustomHTMLTags/transformCustomHTMLTags.ts) and [GodotShortcut.ts](https://github.com/GDQuest/process-course-utils/blob/b973d1ed9fd5b1a37543a88c723ca82e903266ea/src/transformCustomHTMLTags/godotShortcut.ts)
- [ ] Parse MDX components #65
- [ ] Parse and render practices using the MDX components
